<?php

namespace Database\Seeders;

use App\Models\Town;
use Illuminate\Database\Seeder;

class TownSeeder extends Seeder
{
    public function run(): void
    {
        $towns = [
            [
                'slug' => 'laoag-city',
                'name' => 'Laoag City',
                'title' => 'The Sunshine City of the North & Capital of Ilocos Norte',
                'region' => 'Ilocos Norte',
                'description' => 'Laoag City is the vibrant capital of Ilocos Norte, rich in Spanish colonial architecture, cultural heritage landmarks, and bustling commercial districts.',
                'hero_image' => '/assets/images/Laoag.jpg',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'status' => 'published',
                'order' => 1,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'paoay',
                'name' => 'Paoay',
                'title' => 'Home of the UNESCO World Heritage Paoay Church',
                'region' => 'Ilocos Norte',
                'description' => 'Famous for the majestic Saint Augustine Church (Paoay Church), Paoay Lake, historical presidential residences, and thrilling sand dune adventures.',
                'hero_image' => '/assets/images/Paoay.jpg',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'status' => 'published',
                'order' => 2,
                'difficulty_level' => 'Advanced',
            ],
            [
                'slug' => 'pagudpud',
                'name' => 'Pagudpud',
                'title' => 'The Boracay of the North & Eco-Tourism Haven',
                'region' => 'Ilocos Norte',
                'description' => 'Renowned for pristine white sand beaches, Saud Beach, Blue Lagoon, and scenic coastal mountain ranges.',
                'hero_image' => '/assets/images/Pagudpud.jpg',
                'video_url' => null,
                'status' => 'published',
                'order' => 3,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'adams',
                'name' => 'Adams',
                'title' => 'The Eco-Tourism Paradise in the Mountains',
                'region' => 'Ilocos Norte',
                'description' => 'Nestled amidst lush rainforests and waterfalls, home to diverse indigenous cultural communities and eco-adventures.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 4,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'bacarra',
                'name' => 'Bacarra',
                'title' => 'Home of the Beheading Belfry',
                'region' => 'Ilocos Norte',
                'description' => 'Known for its historical ruined bell tower damaged by earthquakes and rich agricultural traditions.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 5,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'badoc',
                'name' => 'Badoc',
                'title' => 'Birthplace of Juan Luna & Sanctuary of La Virgen Milagrosa',
                'region' => 'Ilocos Norte',
                'description' => 'Historic town featuring the Juan Luna Shrine and the Minor Basilica of La Virgen Milagrosa de Badoc.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 6,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'bangui',
                'name' => 'Bangui',
                'title' => 'Pioneer of Wind Energy in Southeast Asia',
                'region' => 'Ilocos Norte',
                'description' => 'Iconic destination famous for the giant Bangui Windmills along Bangui Bay.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 7,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'banna',
                'name' => 'Banna',
                'title' => 'Rice & Agriculture Hub',
                'region' => 'Ilocos Norte',
                'description' => 'Celebrated for rice production, traditional crafts, and peaceful countryside scenery.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 8,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'burgos',
                'name' => 'Burgos',
                'title' => 'Home of Cape Bojeador Lighthouse & Kapurpurawan Rock Formation',
                'region' => 'Ilocos Norte',
                'description' => 'Stunning coastal landscapes, natural white limestone cliffs, and historic lighthouse built in 1892.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 9,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'carasi',
                'name' => 'Carasi',
                'title' => 'Nature & River Sanctuary',
                'region' => 'Ilocos Norte',
                'description' => 'Quiet upland town known for clear river systems, waterfalls, and eco-trekking routes.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 10,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'currimao',
                'name' => 'Currimao',
                'title' => 'Port Town & Coral Rock Formations',
                'region' => 'Ilocos Norte',
                'description' => 'Features calm beaches, ancient coral rock formations, and port facilities.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 11,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'dingras',
                'name' => 'Dingras',
                'title' => 'Rice Granary of Ilocos Norte',
                'region' => 'Ilocos Norte',
                'description' => 'Agricultural powerhouse with historic brick church ruins of St. Joseph Parish.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 12,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'dumalneg',
                'name' => 'Dumalneg',
                'title' => 'Cultural Ancestral Domain',
                'region' => 'Ilocos Norte',
                'description' => 'Home to indigenous Isnag communities preserving rich traditional customs.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 13,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'marcos',
                'name' => 'Marcos',
                'title' => 'Lush Valleys & Eco-Farm Sites',
                'region' => 'Ilocos Norte',
                'description' => 'Known for agricultural productivity, caves, and scenic valley hills.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 14,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'nueva-era',
                'name' => 'Nueva Era',
                'title' => 'Tingguian Heritage & Eco-Cultural Park',
                'region' => 'Ilocos Norte',
                'description' => 'Cultural destination celebrating Tingguian indigenous traditions and mountain resort experiences.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 15,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'pasuquin',
                'name' => 'Pasuquin',
                'title' => 'Salt Capital & Biscotcho Delicacy Hub',
                'region' => 'Ilocos Norte',
                'description' => 'Famous for coastal salt-making farms and the delicious Ilocano biscotcho pastry.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 16,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'piddig',
                'name' => 'Piddig',
                'title' => 'Home of Basi Revolt & Coffee Capital',
                'region' => 'Ilocos Norte',
                'description' => 'Historical town famous for the 1807 Basi Revolt and thriving high-quality coffee plantations.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 17,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'pinili',
                'name' => 'Pinili',
                'title' => 'Land of Abel Weaving & Magdalena Gamayo',
                'region' => 'Ilocos Norte',
                'description' => 'Home of National Living Treasure (Gawad sa Manlilikha ng Bayan) Magdalena Gamayo and traditional Inabel weaving.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 18,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'san-nicolas',
                'name' => 'San Nicolas',
                'title' => 'Pottery & Damili Heritage Capital',
                'region' => 'Ilocos Norte',
                'description' => 'Town famed for ancient terracotta pottery making (Damili) and commercial shopping centers.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 19,
                'difficulty_level' => 'Beginner',
            ],
            [
                'slug' => 'sarrat',
                'name' => 'Sarrat',
                'title' => 'Birthplace of Ferdinand E. Marcos & Santa Monica Parish',
                'region' => 'Ilocos Norte',
                'description' => 'Boasts the largest church in the Ilocos Region (Santa Monica Parish) and rich historical landmarks.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 20,
                'difficulty_level' => 'Intermediate',
            ],
            [
                'slug' => 'vintar',
                'name' => 'Vintar',
                'title' => 'Eco-Adventure Park & Vintar Dam',
                'region' => 'Ilocos Norte',
                'description' => 'Largest municipality by land area, famous for the Umok ni Siwawer nature park and zip-line adventure.',
                'hero_image' => '/assets/images/INBackground.jpg',
                'status' => 'published',
                'order' => 21,
                'difficulty_level' => 'Intermediate',
            ],
        ];

        foreach ($towns as $town) {
            Town::updateOrCreate(['slug' => $town['slug']], $town);
        }
    }
}
